### PR TITLE
Add my name

### PR DESCRIPTION
**Pull request by cap10morgan**

### CODE REVIEW

**Comment by cap10morgan** [comment]
Not sure why my commit is trying to remove names. Should I submit a new PR?

**Comment by dbp** [comment]
If you'd like. Or I can fix when I merge.

It's caused by commits merged while you were editing, I believe.

**Comment by cap10morgan** [comment]
@dbp OK, I'll leave it to you then. Sounds like it could just happen again anyway if I issue a new PR. Thanks!

**Comment by dbp** [comment]
No problem - it's already fixed.

**Pull request merged**
